<?php

use Illuminate\Database\Seeder;

class TermsTableSeeder extends Seeder
{
    // TODO　後からまとめてinsert でいい
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('japanese_terms')->insert(
            [
                ['term' => '消化器学', 'department' => '消化器'],
                ['term' => '空腸', 'department' => '消化器'],
                ['term' => '回腸', 'department' => '消化器'],
                ['term' => '盲腸', 'department' => '消化器'],
                ['term' => '憩室', 'department' => '消化器'],
                ['term' => '消化', 'department' => '消化器'],
                ['term' => '消化不良', 'department' => '消化器'],
                ['term' => '嚥下障害', 'department' => '消化器'],
                ['term' => '胸やけ', 'department' => '消化器'],
                ['term' => '吐血', 'department' => '消化器'],
                ['term' => '下血', 'department' => '消化器'],
                ['term' => '便秘', 'department' => '消化器'],
                ['term' => '腹部膨満感', 'department' => '消化器'],
                ['term' => '膨隆', 'department' => '消化器'],
                ['term' => '胃食道逆流症', 'department' => '消化器'],
                ['term' => '食道静脈瘤', 'department' => '消化器'],
                ['term' => '腸重積', 'department' => '消化器'],
                ['term' => '潰瘍性大腸炎', 'department' => '消化器'],
                ['term' => '汎発性腹膜炎', 'department' => '消化器'],
                ['term' => '過敏性腸症候群', 'department' => '消化器'],
                ['term' => '痔核', 'department' => '消化器'],
                ['term' => '総胆管', 'department' => '消化器'],
                ['term' => '胆嚢管', 'department' => '消化器'],
                ['term' => '胆汁', 'department' => '消化器'],
                ['term' => '腹水', 'department' => '消化器'],
                ['term' => '黄疸', 'department' => '消化器'],
                ['term' => '肝性脳症', 'department' => '消化器'],
                ['term' => '胆管炎', 'department' => '消化器'],
                ['term' => '胆嚢炎', 'department' => '消化器'],
                ['term' => '狭心症', 'department' => '循環器'],
                ['term' => '心筋症', 'department' => '循環器'],
                ['term' => '動脈瘤', 'department' => '循環器'],
                ['term' => '弁膜症', 'department' => '循環器'],
                ['term' => '心臓病学', 'department' => '循環器'],
                ['term' => '上腕動脈', 'department' => '循環器'],
                ['term' => '大腿動脈', 'department' => '循環器'],
                ['term' => '動脈硬化', 'department' => '循環器'],
                ['term' => '心内膜炎', 'department' => '循環器'],
                ['term' => '心房細動', 'department' => '循環器'],
                ['term' => '橈側皮静脈', 'department' => '循環器'],
                ['term' => '大動脈弁狭窄症', 'department' => '循環器'],
                ['term' => 'アテローム硬化', 'department' => '循環器'],
                ['term' => '大動脈弁閉鎖不全', 'department' => '循環器'],
                ['term' => '内分泌学', 'department' => '内分泌'],
                ['term' => '視床下部', 'department' => '内分泌'],
                ['term' => '下垂体',  'department' => '内分泌'],
                ['term' => '副腎', 'department' => '内分泌'],
                ['term' => '副腎皮質', 'department' => '内分泌'],
                ['term' => '副腎髄質', 'department' => '内分泌'],
                ['term' => '膵島',  'department' => '内分泌'],
                ['term' => '外分泌', 'department' => '内分泌'],
                ['term' => 'るいそう', 'department' => '内分泌'],
                ['term' => '脂質異常症', 'department' => '内分泌'],
                ['term' => '痛風',  'department' => '内分泌'],
                ['term' => '骨粗鬆症', 'department' => '内分泌'],
                ['term' => '先端巨大症', 'department' => '内分泌'],
                ['term' => '甲状腺腫', 'department' => '内分泌'],
                ['term' => '糸球体', 'department' => '腎臓'],
                ['term' => '尿細管', 'department' => '腎臓'],
                ['term' => 'ネフローゼ', 'department' => '腎臓'],
                ['term' => '尿毒症', 'department' => '腎臓'],
                ['term' => '血液透析', 'department' => '腎臓'],
                ['term' => '腹膜透析', 'department' => '腎臓'],
                ['term' => '利尿薬', 'department' => '腎臓'],
                ['term' => '血液学',  'department' => '血液'],
                ['term' => '拒絶反応', 'department' => '血液'],
                ['term' => '自己抗体', 'department' => '血液'],
                ['term' => '免疫寛容', 'department' => '血液'],
                ['term' => '骨髄',  'department' => '血液'],
                ['term' => '胸腺', 'department' => '血液'],
                ['term' => '血算', 'department' => '血液'],
                ['term' => '赤血球', 'department' => '血液'],
                ['term' => '白血球',  'department' => '血液'],
                ['term' => '好酸球',  'department' => '血液'],
                ['term' => '好中球',  'department' => '血液'],
                ['term' => '好塩基球', 'department' => '血液'],
                ['term' => '血栓',  'department' => '血液'],
                ['term' => '塞栓',  'department' => '血液'],
                ['term' => '脾腫',  'department' => '血液'],
                ['term' => '貧血',  'department' => '血液'],
                ['term' => '血清',  'department' => '血液'],
                ['term' => '血漿',  'department' => '血液'],
                ['term' => '赤沈', 'department' => '血液'],
                ['term' => '輸血', 'department' => '血液'],
                ['term' => '移植', 'department' => '血液'],
                ['term' => '白血病', 'department' => '血液'],
                ['term' => '血友病', 'department' => '血液'],
                ['term' => '培養', 'department' => '感染症'],
                ['term' => '検疫', 'department' => '感染症'],
                ['term' => '隔離', 'department' => '感染症'],
                ['term' => '滅菌', 'department' => '感染症'],
                ['term' => '真菌', 'department' => '感染症'],
                ['term' => '水痘', 'department' => '感染症'],
                ['term' => '麻疹', 'department' => '感染症'],
                ['term' => '風疹', 'department' => '感染症'],
                ['term' => '結核', 'department' => '感染症'],
                ['term' => '赤痢', 'department' => '感染症'],
                ['term' => '病原体', 'department' => '感染症'],
                ['term' => '寄生虫', 'department' => '感染症'],
                ['term' => '百日咳', 'department' => '感染症'],
                ['term' => '破傷風',  'department' => '感染症'],
                ['term' => '髄膜炎',  'department' => '感染症'],
                ['term' => 'コレラ',  'department' => '感染症'],
                ['term' => '市中肺炎', 'department' => '感染症'],
                ['term' => 'プリオン', 'department' => '感染症'],
                ['term' => 'マラリア',  'department' => '感染症'],
                ['term' => '院内感染', 'department' => '感染症'],
                ['term' => '予防接種',  'department' => '感染症'],
                ['term' => 'クラミジア', 'department' => '感染症'],
                ['term' => 'グラム染色', 'department' => '感染症'],
                ['term' => '気管', 'department' => '呼吸器'],
                ['term' => '縦隔', 'department' => '呼吸器'],
                ['term' => '胸郭', 'department' => '呼吸器'],
                ['term' => '乳腺', 'department' => '呼吸器'],
                ['term' => '腋窩', 'department' => '呼吸器'],
                ['term' => '喀痰', 'department' => '呼吸器'],
                ['term' => '喀血', 'department' => '呼吸器'],
                ['term' => '嗄声', 'department' => '呼吸器'],
                ['term' => '気胸', 'department' => '呼吸器'],
                ['term' => '気管支', 'department' => '呼吸器'],
                ['term' => 'いびき', 'department' => '呼吸器'],
                ['term' => '乳腺症',  'department' => '呼吸器'],
                ['term' => '無呼吸',  'department' => '呼吸器'],
                ['term' => '肺水腫',  'department' => '呼吸器'],
                ['term' => 'ばち指', 'department' => '呼吸器'],
                ['term' => '無気肺', 'department' => '呼吸器'],
                ['term' => '気管支炎', 'department' => '呼吸器'],
                ['term' => '呼吸困難', 'department' => '呼吸器'],
                ['term' => 'チアノーゼ', 'department' => '呼吸器'],
                ['term' => '気管分岐部', 'department' => '呼吸器'],
                ['term' => '間質性肺炎', 'department' => '呼吸器'],
                ['term' => '過換気症候群', 'department' => '呼吸器'],
                ['term' => '睡眠時無呼吸症候群', 'department' => '呼吸器'],
                ['term' => '橋', 'department' => '神経'],
                ['term' => '大脳', 'department' => '神経'],
                ['term' => '延髄', 'department' => '神経'],
                ['term' => '痙攣', 'department' => '神経'],
                ['term' => '振戦', 'department' => '神経'],
                ['term' => '失調', 'department' => '神経'],
                ['term' => '無動', 'department' => '神経'],
                ['term' => '強直', 'department' => '神経'],
                ['term' => '萎縮', 'department' => '神経'],
                ['term' => '中脳', 'department' => '神経'],
                ['term' => '小脳', 'department' => '神経'],
                ['term' => '視床', 'department' => '神経'],
                ['term' => 'しびれ', 'department' => '神経'],
                ['term' => '筋緊張', 'department' => '神経'],
                ['term' => '筋強剛', 'department' => '神経'],
                ['term' => '髄膜腫', 'department' => '神経'],
                ['term' => '片頭痛', 'department' => '神経'],
                ['term' => '脳梗塞', 'department' => '神経'],
                ['term' => '脳出血', 'department' => '神経'],
                ['term' => '前頭葉', 'department' => '神経'],
                ['term' => '頭頂葉', 'department' => '神経'],
                ['term' => '側頭葉', 'department' => '神経'],
                ['term' => '後頭葉', 'department' => '神経'],
                ['term' => '脳神経', 'department' => '神経'],
                ['term' => '反回神経', 'department' => '神経'],
                ['term' => '自律神経', 'department' => '神経'],
                ['term' => '交感神経', 'department' => '神経'],
                ['term' => '脳脊髄液', 'department' => '神経'],
                ['term' => 'てんかん', 'department' => '神経'],
                ['term' => '熱性痙攣', 'department' => '神経'],
                ['term' => '群発頭痛', 'department' => '神経'],
                ['term' => '脳性麻痺', 'department' => '神経'],
                ['term' => '神経膠腫', 'department' => '神経'],
                ['term' => '脳波検査', 'department' => '神経'],
                ['term' => '腰椎穿刺', 'department' => '神経'],
                ['term' => '硬膜下出血', 'department' => '神経'],
                ['term' => '動静脈奇形', 'department' => '神経'],
                ['term' => '舞踏様運動', 'department' => '神経'],
                ['term' => '神経内科学', 'department' => '神経'],
                ['term' => '緊張型頭痛', 'department' => '神経'],
                ['term' => '副交感神経', 'department' => '神経'],
                ['term' => 'くも膜下出血', 'department' => '神経'],
                ['term' => 'てんかん発作', 'department' => '神経'],
                ['term' => '脳神経外科学', 'department' => '神経'],
                ['term' => '重症筋無力症', 'department' => '神経'],
                ['term' => '見当識障害', 'department' => '救急'],
                ['term' => '意識障害', 'department' => '救急'],
                ['term' => '気道閉塞', 'department' => '救急'],
                ['term' => '打撲傷', 'department' => '救急'],
                ['term' => '擦過傷', 'department' => '救急'],
                ['term' => '脳振盪', 'department' => '救急'],
                ['term' => '熱中症', 'department' => '救急'],
                ['term' => '気絶', 'department' => '救急'],
                ['term' => '中毒', 'department' => '救急'],
                ['term' => '乱用', 'department' => '救急'],
                ['term' => '発汗', 'department' => '救急'],
                ['term' => '血腫', 'department' => '救急'],
                ['term' => '挿管', 'department' => '救急'],
                ['term' => 'デブリドマン', 'department' => '救急'],
                ['term' => '自動体外式除細動器', 'department' => '救急'],
                ['term' => '全身麻酔', 'department' => '麻酔'],
                ['term' => '局所麻酔', 'department' => '麻酔'],
                ['term' => '完全静脈麻酔', 'department' => '麻酔'],
                ['term' => '入院', 'department' => '総論'],
                ['term' => '外来', 'department' => '総論'],
                ['term' => '禁忌', 'department' => '総論'],
                ['term' => '退院', 'department' => '総論'],
                ['term' => '消毒', 'department' => '総論'],
                ['term' => '用法', 'department' => '総論'],
                ['term' => '適応', 'department' => '総論'],
                ['term' => '生検', 'department' => '総論'],
                ['term' => '視診', 'department' => '総論'],
                ['term' => '同側', 'department' => '総論'],
                ['term' => '診察', 'department' => '総論'],
                ['term' => '打診', 'department' => '総論'],
                ['term' => '聴診', 'department' => '総論'],
                ['term' => '触診', 'department' => '総論'],
                ['term' => '耳鏡', 'department' => '総論'],
                ['term' => '腫脹', 'department' => '総論'],
                ['term' => '肥大', 'department' => '総論'],
                ['term' => '播種', 'department' => '総論'],
                ['term' => '青年', 'department' => '総論'],
                ['term' => '患側', 'department' => '総論'],
                ['term' => '鼻汁', 'department' => '総論'],
                ['term' => '近位', 'department' => '総論'],
                ['term' => '対側', 'department' => '総論'],
                ['term' => '腹側', 'department' => '総論'],
                ['term' => '背側', 'department' => '総論'],
                ['term' => '頭側', 'department' => '総論'],
                ['term' => '尾側', 'department' => '総論'],
                ['term' => '悪寒', 'department' => '総論'],
                ['term' => '前兆', 'department' => '総論'],
                ['term' => '寛解', 'department' => '総論'],
                ['term' => '術後補助化学療法', 'department' => '総論'],
                ['term' => '細胞診', 'department' => '総論'],
                ['term' => '眼底鏡', 'department' => '総論'],
                ['term' => '血圧計', 'department' => '総論'],
                ['term' => '体温計', 'department' => '総論'],
                ['term' => '舌圧子', 'department' => '総論'],
                ['term' => '聴診器', 'department' => '総論'],
                ['term' => '散発性', 'department' => '総論'],
                ['term' => '遺伝性', 'department' => '総論'],
                ['term' => '医原性', 'department' => '総論'],
                ['term' => '特発性', 'department' => '総論'],
                ['term' => '続発性', 'department' => '総論'],
                ['term' => '処方箋', 'department' => '総論'],
                ['term' => '先天性', 'department' => '総論'],
                ['term' => '広汎性', 'department' => '総論'],
                ['term' => '腹臥位', 'department' => '総論'],
                ['term' => '背臥位', 'department' => '総論'],
                ['term' => '側臥位', 'department' => '総論'],
                ['term' => '砕石位', 'department' => '総論'],
                ['term' => '間欠的', 'department' => '総論'],
                ['term' => '持続的', 'department' => '総論'],
                ['term' => '薬理学', 'department' => '総論'],
                ['term' => '間欠痛', 'department' => '総論'],
                ['term' => '外用治療', 'department' => '総論'],
                ['term' => '緩和医療', 'department' => '総論'],
                ['term' => '顔面蒼白', 'department' => '総論'],
                ['term' => '局所再発', 'department' => '総論'],
                ['term' => '鑑別診断', 'department' => '総論'],
                ['term' => '臨床症状', 'department' => '総論'],
                ['term' => '身体診察', 'department' => '総論'],
                ['term' => '触知可能の', 'department' => '総論'],
                ['term' => '生理食塩水', 'department' => '総論'],
                ['term' => '全身倦怠感', 'department' => '総論'],
                ['term' => '形成外科学', 'department' => '総論'],
                ['term' => '小児科学', 'department' => '小児科'],
                ['term' => '授乳', 'department' => '小児科'],
                ['term' => '離乳', 'department' => '小児科'],
                ['term' => '口蓋裂', 'department' => '小児科'],
                ['term' => '婦人科学', 'department' => '産婦人科'],
                ['term' => '産科学',  'department' => '産婦人科'],
                ['term' => '骨盤', 'department' => '産婦人科'],
                ['term' => '子宮', 'department' => '産婦人科'],
                ['term' => '胎盤', 'department' => '産婦人科'],
                ['term' => '卵管', 'department' => '産婦人科'],
                ['term' => '受精', 'department' => '産婦人科'],
                ['term' => '人工妊娠中絶', 'department' => '産婦人科'],
                ['term' => '自然流産',  'department' => '産婦人科'],
                ['term' => '無月経', 'department' => '産婦人科'],
                ['term' => '月経困難', 'department' => '産婦人科'],
                ['term' => 'つわり', 'department' => '産婦人科'],
                ['term' => '帯下',  'department' => '産婦人科'],
                ['term' => '胎芽', 'department' => '産婦人科'],
                ['term' => '胎児', 'department' => '産婦人科'],
                ['term' => '閉経', 'department' => '産婦人科'],
                ['term' => '子宮内膜症',  'department' => '産婦人科'],
                ['term' => '子宮外妊娠', 'department' => '産婦人科'],
                ['term' => '更年期障害', 'department' => '産婦人科'],
                ['term' => '妊娠検査',  'department' => '産婦人科'],
                ['term' => '経口避妊薬', 'department' => '産婦人科'],
                ['term' => '不妊手術', 'department' => '産婦人科'],
                ['term' => '帝王切開', 'department' => '産婦人科'],
                ['term' => '眼科学', 'department' => '眼科'],
                ['term' => '角膜',  'department' => '眼科'],
                ['term' => 'ぶどう膜', 'department' => '眼科'],
                ['term' => '脈絡膜',  'department' => '眼科'],
                ['term' => '虹彩', 'department' => '眼科'],
                ['term' => '硝子体', 'department' => '眼科'],
                ['term' => '強膜', 'department' => '眼科'],
                ['term' => '眼瞼', 'department' => '眼科'],
                ['term' => '眼球結膜', 'department' => '眼科'],
                ['term' => '眼瞼結膜', 'department' => '眼科'],
                ['term' => '近視', 'department' => '眼科'],
                ['term' => '遠視', 'department' => '眼科'],
                ['term' => '斜視', 'department' => '眼科'],
                ['term' => '複視', 'department' => '眼科'],
                ['term' => '飛蚊症', 'department' => '眼科'],
                ['term' => '充血', 'department' => '眼科'],
                ['term' => '結膜炎', 'department' => '眼科'],
                ['term' => '角膜炎', 'department' => '眼科'],
                ['term' => '白内障', 'department' => '眼科'],
                ['term' => '緑内障', 'department' => '眼科'],
                ['term' => '網膜剥離', 'department' => '眼科'],
                ['term' => '耳鼻咽喉科学', 'department' => '耳鼻咽喉科'],
                ['term' => '蝸牛', 'department' => '耳鼻咽喉科'],
                ['term' => '舌', 'department' => '耳鼻咽喉科'],
                ['term' => '咽頭', 'department' => '耳鼻咽喉科'],
                ['term' => '喉頭', 'department' => '耳鼻咽喉科'],
                ['term' => '副鼻腔', 'department' => '耳鼻咽喉科'],
                ['term' => '耳鳴', 'department' => '耳鼻咽喉科'],
                ['term' => '浮動性めまい', 'department' => '耳鼻咽喉科'],
                ['term' => '回転性めまい', 'department' => '耳鼻咽喉科'],
                ['term' => '眼振', 'department' => '耳鼻咽喉科'],
                ['term' => '難聴', 'department' => '耳鼻咽喉科'],
                ['term' => '鼻出血', 'department' => '耳鼻咽喉科'],
                ['term' => '喉頭炎', 'department' => '耳鼻咽喉科'],
                ['term' => '扁桃炎', 'department' => '耳鼻咽喉科'],
                ['term' => '中耳炎', 'department' => '耳鼻咽喉科'],
                ['term' => '副鼻腔炎', 'department' => '耳鼻咽喉科'],
                ['term' => '整形外科学', 'department' => '整形外科'],
                ['term' => '腱', 'department' => '整形外科'],
                ['term' => '軟骨', 'department' => '整形外科'],
                ['term' => '滑膜', 'department' => '整形外科'],
                ['term' => '外転', 'department' => '整形外科'],
                ['term' => '内転', 'department' => '整形外科'],
                ['term' => '屈曲', 'department' => '整形外科'],
                ['term' => '伸展', 'department' => '整形外科'],
                ['term' => '弛緩', 'department' => '整形外科'],
                ['term' => '収縮', 'department' => '整形外科'],
                ['term' => '四肢', 'department' => '整形外科'],
                ['term' => '跛行', 'department' => '整形外科'],
                ['term' => '間欠性跛行', 'department' => '整形外科'],
                ['term' => '関節リウマチ', 'department' => '整形外科'],
                ['term' => '変形性関節症', 'department' => '整形外科'],
                ['term' => '関節炎', 'department' => '整形外科'],
                ['term' => '椎間板ヘルニア', 'department' => '整形外科'],
                ['term' => '脊柱菅狭窄症', 'department' => '整形外科'],
                ['term' => '脊柱側彎症',  'department' => '整形外科'],
                ['term' => '徒手筋力検査', 'department' => '整形外科'],
                ['term' => '筋電図検査', 'department' => '整形外科'],
                ['term' => '脱臼',  'department' => '整形外科'],
                ['term' => '精神科学', 'department' => '精神科'],
                ['term' => '不眠症', 'department' => '精神科'],
                ['term' => '幻覚',  'department' => '精神科'],
                ['term' => '妄想',  'department' => '精神科'],
                ['term' => '不安',  'department' => '精神科'],
                ['term' => '不隠',  'department' => '精神科'],
                ['term' => '躁状態', 'department' => '精神科'],
                ['term' => '食思不振', 'department' => '精神科'],
                ['term' => 'せん妄', 'department' => '精神科'],
                ['term' => '躁病', 'department' => '精神科'],
                ['term' => '統合失調症', 'department' => '精神科'],
                ['term' => 'ヒステリー', 'department' => '精神科'],
                ['term' => '自閉症', 'department' => '精神科'],
                ['term' => '皮膚科学', 'department' => '皮膚科'],
                ['term' => '掻痒', 'department' => '皮膚科'],
                ['term' => '褥瘡', 'department' => '皮膚科'],
                ['term' => '紅斑', 'department' => '皮膚科'],
                ['term' => '紫斑', 'department' => '皮膚科'],
                ['term' => '丘疹', 'department' => '皮膚科'],
                ['term' => '結節', 'department' => '皮膚科'],
                ['term' => '水疱', 'department' => '皮膚科'],
                ['term' => 'びらん', 'department' => '皮膚科'],
                ['term' => '湿疹', 'department' => '皮膚科'],
                ['term' => '蕁麻疹', 'department' => '皮膚科'],
                ['term' => '薬疹', 'department' => '皮膚科'],
                ['term' => 'アトピー性皮膚炎','department' => '皮膚科'],
                ['term' => '膿疱', 'department' => '皮膚科'],
                ['term' => '帯状疱疹','department' => '皮膚科'],
                ['term' => '泌尿器科学', 'department' => '泌尿器科'],
                ['term' => '尿管', 'department' => '泌尿器科'],
                ['term' => '尿道', 'department' => '泌尿器科'],
                ['term' => '陰茎', 'department' => '泌尿器科'],
                ['term' => '精子', 'department' => '泌尿器科'],
                ['term' => '多尿', 'department' => '泌尿器科'],
                ['term' => '乏尿', 'department' => '泌尿器科'],
                ['term' => '無尿', 'department' => '泌尿器科'],
                ['term' => '排尿困難', 'department' => '泌尿器科'],
                ['term' => '尿失禁', 'department' => '泌尿器科'],
                ['term' => '蛋白尿', 'department' => '泌尿器科'],
                ['term' => '血尿', 'department' => '泌尿器科'],
                ['term' => '膿尿', 'department' => '泌尿器科'],
                ['term' => '尿路結石', 'department' => '泌尿器科'],
                ['term' => '腎結石', 'department' => '泌尿器科'],
                ['term' => '前立腺肥大症', 'department' => '泌尿器科'],
                ['term' => '放射線化学', 'department' => '放射線科'],
                ['term' => '造影', 'department' => '放射線科'],
                ['term' => '照射', 'department' => '放射線科'],
                ['term' => '介入', 'department' => '公衆衛生'],
                ['term' => '罹患率', 'department' => '公衆衛生'],
                ['term' => '有病率', 'department' => '公衆衛生'],
                ['term' => '的中率', 'department' => '公衆衛生'],
                ['term' => '予防医学', 'department' => '公衆衛生'],
                ['term' => 'がん免疫監視', 'department' => '腫瘍学'],
                ['term' => 'リンパ節腫脹', 'department' => '腫瘍学'],
                ['term' => '局所の', 'department' => '腫瘍学'],
                ['term' => '局所再発', 'department' => '腫瘍学'],
            ]
        );


        DB::table('english_terms')->insert(
            [
                ['term' => 'gastroenterology', 'department' => '消化器'],
                ['term' => 'jejunum', 'department' => '消化器'],
                ['term' => 'ileum', 'department' => '消化器'],
                ['term' => 'cecum', 'department' => '消化器'],
                ['term' => 'diverticulum', 'department' => '消化器'],
                ['term' => 'digestion', 'department' => '消化器'],
                ['term' => 'indigestion', 'department' => '消化器'],
                ['term' => 'dysphagia', 'department' => '消化器'],
                ['term' => 'heartburn', 'department' => '消化器'],
                ['term' => 'hematemesis', 'department' => '消化器'],
                ['term' => 'melena', 'department' => '消化器'],
                ['term' => 'constipation', 'department' => '消化器'],
                ['term' => 'bloating', 'department' => '消化器'],
                ['term' => 'protrusion', 'department' => '消化器'],
                ['term' => 'gastroesophageal reflux disease', 'department' => '消化器'],
                ['term' => 'esophageal varix', 'department' => '消化器'],
                ['term' => 'intussusception', 'department' => '消化器'],
                ['term' => 'ulcerative colitis', 'department' => '消化器'],
                ['term' => 'Pan-peritonitis', 'department' => '消化器'],
                ['term' => 'irritable bowel syndrome', 'department' => '消化器'],
                ['term' => 'hemorrhoid', 'department' => '消化器'],
                ['term' => 'common bile duct', 'department' => '消化器'],
                ['term' => 'cystic duct', 'department' => '消化器'],
                ['term' => 'bile', 'department' => '消化器'],
                ['term' => 'ascites', 'department' => '消化器'],
                ['term' => 'jaundice,icterus', 'department' => '消化器'],
                ['term' => 'hepatic encephalopathy', 'department' => '消化器'],
                ['term' => 'cholangitis', 'department' => '消化器'],
                ['term' => 'cholecystitis', 'department' => '消化器'],
                ['term' => 'angina pectoris', 'department' => '循環器'],
                ['term' => 'cardiomyopathy', 'department' => '循環器'],
                ['term' => 'aneurysm', 'department' => '循環器'],
                ['term' => 'valvular heart disease', 'department' => '循環器'],
                ['term' => 'cardiology', 'department' => '循環器'],
                ['term' => 'brachial artery', 'department' => '循環器'],
                ['term' => 'femoral artery', 'department' => '循環器'],
                ['term' => 'arteriosclerosis', 'department' => '循環器'],
                ['term' => 'endocarditis', 'department' => '循環器'],
                ['term' => 'atrial fibrillation', 'department' => '循環器'],
                ['term' => 'cephalic vein', 'department' => '循環器'],
                ['term' => 'aortic stenosis', 'department' => '循環器'],
                ['term' => 'atherosclerosis', 'department' => '循環器'],
                ['term' => 'aortic regurgitation', 'department' => '循環器'],
                ['term' => 'endocrinology', 'department' => '内分泌'],
                ['term' => 'hypothalamus', 'department' => '内分泌'],
                ['term' => 'pituitary gland', 'department' => '内分泌'],
                ['term' => 'adrenal gland', 'department' => '内分泌'],
                ['term' => 'cortex of the adrenal gland', 'department' => '内分泌'],
                ['term' => 'medulla of the adrenal gland', 'department' => '内分泌'],
                ['term' => 'pancreatic islet', 'department' => '内分泌'],
                ['term' => 'exocrine', 'department' => '内分泌'],
                ['term' => 'emaciation', 'department' => '内分泌'],
                ['term' => 'dyslipidemia', 'department' => '内分泌'],
                ['term' => 'gout', 'department' => '内分泌'],
                ['term' => 'osteoporosis', 'department' => '内分泌'],
                ['term' => 'acromegaly', 'department' => '内分泌'],
                ['term' => 'goiter', 'department' => '内分泌'],
                ['term' => 'glomerulus', 'department' => '腎臓'],
                ['term' => 'renal tubule', 'department' => '腎臓'],
                ['term' => 'nephrosis', 'department' => '腎臓'],
                ['term' => 'uremia', 'department' => '腎臓'],
                ['term' => 'hemodialysis', 'department' => '腎臓'],
                ['term' => 'peritoneal dialysis', 'department' => '腎臓'],
                ['term' => 'diuretic', 'department' => '腎臓'],
                ['term' => 'hematology', 'department' => '血液'],
                ['term' => 'rejection', 'department' => '血液'],
                ['term' => 'autoantibody', 'department' => '血液'],
                ['term' => 'immune tolerance', 'department' => '血液'],
                ['term' => 'bone marrow', 'department' => '血液'],
                ['term' => 'thymus', 'department' => '血液'],
                ['term' => 'complete blood count', 'department' => '血液'],
                ['term' => 'erythrocyte', 'department' => '血液'],
                ['term' => 'leukocyte', 'department' => '血液'],
                ['term' => 'eosinophil', 'department' => '血液'],
                ['term' => 'neutrophil', 'department' => '血液'],
                ['term' => 'basophil', 'department' => '血液'],
                ['term' => 'thrombus', 'department' => '血液'],
                ['term' => 'embolus', 'department' => '血液'],
                ['term' => 'splenomegaly', 'department' => '血液'],
                ['term' => 'anemia', 'department' => '血液'],
                ['term' => 'serum', 'department' => '血液'],
                ['term' => 'plasma', 'department' => '血液'],
                ['term' => 'erythrocyte sedimentation rate', 'department' => '血液'],
                ['term' => 'blood transfusion', 'department' => '血液'],
                ['term' => 'transplantation', 'department' => '血液'],
                ['term' => 'leukemia', 'department' => '血液'],
                ['term' => 'hemophilia', 'department' => '血液'],
                ['term' => 'culture', 'department' => '感染症'],
                ['term' => 'quarantine', 'department' => '感染症'],
                ['term' => 'isolation', 'department' => '感染症'],
                ['term' => 'sterilization', 'department' => '感染症'],
                ['term' => 'fungus', 'department' => '感染症'],
                ['term' => 'varicella', 'department' => '感染症'],
                ['term' => 'measles', 'department' => '感染症'],
                ['term' => 'rubella', 'department' => '感染症'],
                ['term' => 'tuberculosis', 'department' => '感染症'],
                ['term' => 'dysentery', 'department' => '感染症'],
                ['term' => 'pathogen', 'department' => '感染症'],
                ['term' => 'parasite', 'department' => '感染症'],
                ['term' => 'pertussis', 'department' => '感染症'],
                ['term' => 'tetanus', 'department' => '感染症'],
                ['term' => 'meningitis', 'department' => '感染症'],
                ['term' => 'cholera', 'department' => '感染症'],
                ['term' => 'community acquired pneumonia', 'department' => '感染症'],
                ['term' => 'prion', 'department' => '感染症'],
                ['term' => 'malaria', 'department' => '感染症'],
                ['term' => 'nosocomial infection', 'department' => '感染症'],
                ['term' => 'vaccination', 'department' => '感染症'],
                ['term' => 'chlamydia', 'department' => '感染症'],
                ['term' => 'gram stain', 'department' => '感染症'],
                ['term' => 'trachea', 'department' => '呼吸器'],
                ['term' => 'mediastinum', 'department' => '呼吸器'],
                ['term' => 'thorax', 'department' => '呼吸器'],
                ['term' => 'mammary gland', 'department' => '呼吸器'],
                ['term' => 'axilla', 'department' => '呼吸器'],
                ['term' => 'sputum', 'department' => '呼吸器'],
                ['term' => 'hemoptysis', 'department' => '呼吸器'],
                ['term' => 'hoarseness', 'department' => '呼吸器'],
                ['term' => 'pneumothorax', 'department' => '呼吸器'],
                ['term' => 'bronchus', 'department' => '呼吸器'],
                ['term' => 'snoring', 'department' => '呼吸器'],
                ['term' => 'mastopathy', 'department' => '呼吸器'],
                ['term' => 'apnea', 'department' => '呼吸器'],
                ['term' => 'pulmonary edema', 'department' => '呼吸器'],
                ['term' => 'clubbing', 'department' => '呼吸器'],
                ['term' => 'atelectasis', 'department' => '呼吸器'],
                ['term' => 'bronchitis', 'department' => '呼吸器'],
                ['term' => 'dyspnea', 'department' => '呼吸器'],
                ['term' => 'cyanosis', 'department' => '呼吸器'],
                ['term' => 'tracheal bifurcation', 'department' => '呼吸器'],
                ['term' => 'interstitial pneumonia', 'department' => '呼吸器'],
                ['term' => 'hyperventilation syndrome', 'department' => '呼吸器'],
                ['term' => 'sleep apnea syndrome', 'department' => '呼吸器'],
                ['term' => 'pons', 'department' => '神経'],
                ['term' => 'cerebrum', 'department' => '神経'],
                ['term' => 'medulla oblongata', 'department' => '神経'],
                ['term' => 'convulsion', 'department' => '神経'],
                ['term' => 'tremor', 'department' => '神経'],
                ['term' => 'ataxia', 'department' => '神経'],
                ['term' => 'akinesia', 'department' => '神経'],
                ['term' => 'tetany', 'department' => '神経'],
                ['term' => 'atrophy', 'department' => '神経'],
                ['term' => 'midbrain', 'department' => '神経'],
                ['term' => 'cerebellum', 'department' => '神経'],
                ['term' => 'thalamus', 'department' => '神経'],
                ['term' => 'numbness', 'department' => '神経'],
                ['term' => 'muscle tonus', 'department' => '神経'],
                ['term' => 'muscle rigidity', 'department' => '神経'],
                ['term' => 'meningioma', 'department' => '神経'],
                ['term' => 'migraine', 'department' => '神経'],
                ['term' => 'cerebral infarction', 'department' => '神経'],
                ['term' => 'cerebral hemorrhage', 'department' => '神経'],
                ['term' => 'frontal lobe', 'department' => '神経'],
                ['term' => 'parietal lobe', 'department' => '神経'],
                ['term' => 'temporal lobe', 'department' => '神経'],
                ['term' => 'occipital lobe', 'department' => '神経'],
                ['term' => 'cranial nerves', 'department' => '神経'],
                ['term' => 'recurrent laryngeal nerve', 'department' => '神経'],
                ['term' => 'autonomic nerve', 'department' => '神経'],
                ['term' => 'sympathetic nerve', 'department' => '神経'],
                ['term' => 'cerebrospinal fluid', 'department' => '神経'],
                ['term' => 'epilepsy', 'department' => '神経'],
                ['term' => 'febrile convulsion', 'department' => '神経'],
                ['term' => 'cluster headache', 'department' => '神経'],
                ['term' => 'cerebral palsy', 'department' => '神経'],
                ['term' => 'glioma', 'department' => '神経'],
                ['term' => 'electroencephalography', 'department' => '神経'],
                ['term' => 'lumbar puncture', 'department' => '神経'],
                ['term' => 'subdural hemorrhage', 'department' => '神経'],
                ['term' => 'arteriovenous malformation', 'department' => '神経'],
                ['term' => 'chorea', 'department' => '神経'],
                ['term' => 'neurology', 'department' => '神経'],
                ['term' => 'tension-type headache', 'department' => '神経'],
                ['term' => 'parasympathetic nerve', 'department' => '神経'],
                ['term' => 'subarachnoid hemorrhage', 'department' => '神経'],
                ['term' => 'epileptic seizure', 'department' => '神経'],
                ['term' => 'neurosurgery', 'department' => '神経'],
                ['term' => 'myasthenia gravis', 'department' => '神経'],
                ['term' => 'disorientation', 'department' => '救急'],
                ['term' => 'impaired consciousness', 'department' => '救急'],
                ['term' => 'airway obstruction', 'department' => '救急'],
                ['term' => 'contusion', 'department' => '救急'],
                ['term' => 'abrasion', 'department' => '救急'],
                ['term' => 'concussion', 'department' => '救急'],
                ['term' => 'heat stroke', 'department' => '救急'],
                ['term' => 'fainting', 'department' => '救急'],
                ['term' => 'poisoning', 'department' => '救急'],
                ['term' => 'abuse', 'department' => '救急'],
                ['term' => 'perspiration', 'department' => '救急'],
                ['term' => 'hematoma', 'department' => '救急'],
                ['term' => 'intubation', 'department' => '救急'],
                ['term' => 'debridement', 'department' => '救急'],
                ['term' => 'Automated External Defibrillator', 'department' => '救急'],
                ['term' => 'general anesthesia', 'department' => '麻酔'],
                ['term' => 'local anesthesia', 'department' => '麻酔'],
                ['term' => 'total intravenous anesthesia', 'department' => '麻酔'],
                ['term' => 'admission', 'department' => '総論'],
                ['term' => 'outpatient', 'department' => '総論'],
                ['term' => 'contraindication', 'department' => '総論'],
                ['term' => 'discharge', 'department' => '総論'],
                ['term' => 'disinfection', 'department' => '総論'],
                ['term' => 'usage', 'department' => '総論'],
                ['term' => 'indication', 'department' => '総論'],
                ['term' => 'biopsy', 'department' => '総論'],
                ['term' => 'inspection', 'department' => '総論'],
                ['term' => 'ipsilateral', 'department' => '総論'],
                ['term' => 'medical examination', 'department' => '総論'],
                ['term' => 'percussion', 'department' => '総論'],
                ['term' => 'auscultation', 'department' => '総論'],
                ['term' => 'palpation', 'department' => '総論'],
                ['term' => 'otoscope', 'department' => '総論'],
                ['term' => 'swelling', 'department' => '総論'],
                ['term' => 'hypertrophy', 'department' => '総論'],
                ['term' => 'dissemination', 'department' => '総論'],
                ['term' => 'adolescent', 'department' => '総論'],
                ['term' => 'affected side', 'department' => '総論'],
                ['term' => 'nasal discharge', 'department' => '総論'],
                ['term' => 'proximal', 'department' => '総論'],
                ['term' => 'contralateral', 'department' => '総論'],
                ['term' => 'ventral', 'department' => '総論'],
                ['term' => 'dorsal', 'department' => '総論'],
                ['term' => 'cranial', 'department' => '総論'],
                ['term' => 'caudal', 'department' => '総論'],
                ['term' => 'chill', 'department' => '総論'],
                ['term' => 'aura', 'department' => '総論'],
                ['term' => 'remission', 'department' => '総論'],
                ['term' => 'neoadjuvant chemotherapy', 'department' => '総論'],
                ['term' => 'cytology', 'department' => '総論'],
                ['term' => 'ophthalmoscope', 'department' => '総論'],
                ['term' => 'sphygmomanometer', 'department' => '総論'],
                ['term' => 'thermometer', 'department' => '総論'],
                ['term' => 'spatula', 'department' => '総論'],
                ['term' => 'stethoscope', 'department' => '総論'],
                ['term' => 'sporadic', 'department' => '総論'],
                ['term' => 'hereditary', 'department' => '総論'],
                ['term' => 'iatrogenic', 'department' => '総論'],
                ['term' => 'idiopathic', 'department' => '総論'],
                ['term' => 'secondary', 'department' => '総論'],
                ['term' => 'prescription', 'department' => '総論'],
                ['term' => 'congenital', 'department' => '総論'],
                ['term' => 'diffuse', 'department' => '総論'],
                ['term' => 'prone position', 'department' => '総論'],
                ['term' => 'supine position', 'department' => '総論'],
                ['term' => 'lateral position', 'department' => '総論'],
                ['term' => 'lithotomy position', 'department' => '総論'],
                ['term' => 'intermittent', 'department' => '総論'],
                ['term' => 'continuous', 'department' => '総論'],
                ['term' => 'pharmacology', 'department' => '総論'],
                ['term' => 'intermittent pain', 'department' => '総論'],
                ['term' => 'topical therapy', 'department' => '総論'],
                ['term' => 'palliative medicine', 'department' => '総論'],
                ['term' => 'pallor', 'department' => '総論'],
                ['term' => 'recurrence', 'department' => '総論'],
                ['term' => 'differential diagnosis', 'department' => '総論'],
                ['term' => 'clinical presentation', 'department' => '総論'],
                ['term' => 'physical examination', 'department' => '総論'],
                ['term' => 'palpable', 'department' => '総論'],
                ['term' => 'saline', 'department' => '総論'],
                ['term' => 'general malaise', 'department' => '総論'],
                ['term' => 'plastic surgery', 'department' => '総論'],
                ['term' => 'pediatrics', 'department' => '小児科'],
                ['term' => 'lactation', 'department' => '小児科'],
                ['term' => 'delactation', 'department' => '小児科'],
                ['term' => 'cleft palate', 'department' => '小児科'],
                ['term' => 'gynecology', 'department' => '産婦人科'],
                ['term' => 'obstetrics', 'department' => '産婦人科'],
                ['term' => 'pelvis', 'department' => '産婦人科'],
                ['term' => 'uterus', 'department' => '産婦人科'],
                ['term' => 'placenta', 'department' => '産婦人科'],
                ['term' => 'oviduct', 'department' => '産婦人科'],
                ['term' => 'fertilization', 'department' => '産婦人科'],
                ['term' => 'artificial abortion', 'department' => '産婦人科'],
                ['term' => 'spontaneous abortion', 'department' => '産婦人科'],
                ['term' => 'amenorrhea', 'department' => '産婦人科'],
                ['term' => 'dysmenorrhea', 'department' => '産婦人科'],
                ['term' => 'morning sickness', 'department' => '産婦人科'],
                ['term' => 'discharge', 'department' => '産婦人科'],
                ['term' => 'embryo', 'department' => '産婦人科'],
                ['term' => 'fetus', 'department' => '産婦人科'],
                ['term' => 'menopause', 'department' => '産婦人科'],
                ['term' => 'endometriosis', 'department' => '産婦人科'],
                ['term' => 'ectopic pregnancy', 'department' => '産婦人科'],
                ['term' => 'menopausal symptom', 'department' => '産婦人科'],
                ['term' => 'pregnancy test', 'department' => '産婦人科'],
                ['term' => 'oral contraceptive', 'department' => '産婦人科'],
                ['term' => 'sterilization', 'department' => '産婦人科'],
                ['term' => 'caesarean section', 'department' => '産婦人科'],
                ['term' => 'ophthalmology', 'department' => '眼科'],
                ['term' => 'cornea', 'department' => '眼科'],
                ['term' => 'uvea', 'department' => '眼科'],
                ['term' => 'chorioidea', 'department' => '眼科'],
                ['term' => 'iris', 'department' => '眼科'],
                ['term' => 'vitreous body', 'department' => '眼科'],
                ['term' => 'sclera', 'department' => '眼科'],
                ['term' => 'eyelid,palpebra', 'department' => '眼科'],
                ['term' => 'bulbar conjunctiva', 'department' => '眼科'],
                ['term' => 'palpebral conjunctiva', 'department' => '眼科'],
                ['term' => 'myopia', 'department' => '眼科'],
                ['term' => 'hyperopia', 'department' => '眼科'],
                ['term' => 'squinting', 'department' => '眼科'],
                ['term' => 'diplopia', 'department' => '眼科'],
                ['term' => 'floater', 'department' => '眼科'],
                ['term' => 'hyperemia', 'department' => '眼科'],
                ['term' => 'conjunctivitis', 'department' => '眼科'],
                ['term' => 'keratitis', 'department' => '眼科'],
                ['term' => 'cataract', 'department' => '眼科'],
                ['term' => 'glaucoma', 'department' => '眼科'],
                ['term' => 'retinal detachment', 'department' => '眼科'],
                ['term' => 'otorhinolaryngology', 'department' => '耳鼻咽喉科'],
                ['term' => 'cochlea', 'department' => '耳鼻咽喉科'],
                ['term' => 'tongue', 'department' => '耳鼻咽喉科'],
                ['term' => 'pharynx', 'department' => '耳鼻咽喉科'],
                ['term' => 'larynx', 'department' => '耳鼻咽喉科'],
                ['term' => 'paranasal sinus', 'department' => '耳鼻咽喉科'],
                ['term' => 'tinnitus', 'department' => '耳鼻咽喉科'],
                ['term' => 'dizziness', 'department' => '耳鼻咽喉科'],
                ['term' => 'vertigo', 'department' => '耳鼻咽喉科'],
                ['term' => 'nystagmus', 'department' => '耳鼻咽喉科'],
                ['term' => 'deafness', 'department' => '耳鼻咽喉科'],
                ['term' => 'epistaxis', 'department' => '耳鼻咽喉科'],
                ['term' => 'laryngitis', 'department' => '耳鼻咽喉科'],
                ['term' => 'tonsillitis', 'department' => '耳鼻咽喉科'],
                ['term' => 'otitis media', 'department' => '耳鼻咽喉科'],
                ['term' => 'sinusitis', 'department' => '耳鼻咽喉科'],
                ['term' => 'orthopedics', 'department' => '整形外科'],
                ['term' => 'tendon', 'department' => '整形外科'],
                ['term' => 'cartilage', 'department' => '整形外科'],
                ['term' => 'synovium', 'department' => '整形外科'],
                ['term' => 'abduction', 'department' => '整形外科'],
                ['term' => 'adduction', 'department' => '整形外科'],
                ['term' => 'flexion', 'department' => '整形外科'],
                ['term' => 'extension', 'department' => '整形外科'],
                ['term' => 'relaxation', 'department' => '整形外科'],
                ['term' => 'contraction', 'department' => '整形外科'],
                ['term' => 'extremities', 'department' => '整形外科'],
                ['term' => 'claudication,limping', 'department' => '整形外科'],
                ['term' => 'intermittent claudication', 'department' => '整形外科'],
                ['term' => 'rheumatoid arthritis', 'department' => '整形外科'],
                ['term' => 'osteoarthritis', 'department' => '整形外科'],
                ['term' => 'arthritis', 'department' => '整形外科'],
                ['term' => 'disk herniation', 'department' => '整形外科'],
                ['term' => 'spinal stenosis', 'department' => '整形外科'],
                ['term' => 'scoliosis', 'department' => '整形外科'],
                ['term' => 'manual muscle test', 'department' => '整形外科'],
                ['term' => 'electromyography', 'department' => '整形外科'],
                ['term' => 'dislocation', 'department' => '整形外科'],
                ['term' => 'psychiatry', 'department' => '精神科'],
                ['term' => 'insomnia', 'department' => '精神科'],
                ['term' => 'hallucination', 'department' => '精神科'],
                ['term' => 'delusion', 'department' => '精神科'],
                ['term' => 'anxiety', 'department' => '精神科'],
                ['term' => 'agitation', 'department' => '精神科'],
                ['term' => 'manic state', 'department' => '精神科'],
                ['term' => 'anorexia', 'department' => '精神科'],
                ['term' => 'delirium', 'department' => '精神科'],
                ['term' => 'mania', 'department' => '精神科'],
                ['term' => 'schizophrenia', 'department' => '精神科'],
                ['term' => 'hysteria', 'department' => '精神科'],
                ['term' => 'autism', 'department' => '精神科'],
                ['term' => 'dermatology', 'department' => '皮膚科'],
                ['term' => 'itching', 'department' => '皮膚科'],
                ['term' => 'decubitus', 'department' => '皮膚科'],
                ['term' => 'erythema', 'department' => '皮膚科'],
                ['term' => 'purpura', 'department' => '皮膚科'],
                ['term' => 'papule', 'department' => '皮膚科'],
                ['term' => 'node', 'department' => '皮膚科'],
                ['term' => 'blister', 'department' => '皮膚科'],
                ['term' => 'erosion', 'department' => '皮膚科'],
                ['term' => 'eczema', 'department' => '皮膚科'],
                ['term' => 'urticaria', 'department' => '皮膚科'],
                ['term' => 'drug eruption', 'department' => '皮膚科'],
                ['term' => 'atopic dermatitis', 'department' => '皮膚科'],
                ['term' => 'pustule', 'department' => '皮膚科'],
                ['term' => 'herpes zoster', 'department' => '皮膚科'],
                ['term' => 'urology', 'department' => '泌尿器科'],
                ['term' => 'ureter', 'department' => '泌尿器科'],
                ['term' => 'urethra', 'department' => '泌尿器科'],
                ['term' => 'penis', 'department' => '泌尿器科'],
                ['term' => 'sperm', 'department' => '泌尿器科'],
                ['term' => 'polyuria', 'department' => '泌尿器科'],
                ['term' => 'oliguria', 'department' => '泌尿器科'],
                ['term' => 'anuria', 'department' => '泌尿器科'],
                ['term' => 'dysuria', 'department' => '泌尿器科'],
                ['term' => 'urinary incontinence', 'department' => '泌尿器科'],
                ['term' => 'proteinuria', 'department' => '泌尿器科'],
                ['term' => 'hematuria', 'department' => '泌尿器科'],
                ['term' => 'pyuria', 'department' => '泌尿器科'],
                ['term' => 'urolithiasis', 'department' => '泌尿器科'],
                ['term' => 'renal stone', 'department' => '泌尿器科'],
                ['term' => 'benign prostatic hyperplasia', 'department' => '泌尿器科'],
                ['term' => 'radiology', 'department' => '放射線科'],
                ['term' => 'imaging', 'department' => '放射線科'],
                ['term' => 'irradiation', 'department' => '放射線科'],
                ['term' => 'intervention', 'department' => '公衆衛生'],
                ['term' => 'morbidity rate', 'department' => '公衆衛生'],
                ['term' => 'prevalence rate', 'department' => '公衆衛生'],
                ['term' => 'predictive value', 'department' => '公衆衛生'],
                ['term' => 'preventive medicine', 'department' => '公衆衛生'],
                ['term' => 'cancer immunosurveillance', 'department' => '腫瘍学'],
                ['term' => 'lymphadenopathy', 'department' => '腫瘍学'],
                ['term' => 'locoregional', 'department' => '腫瘍学'],
                ['term' => 'locoregional recurrence', 'department' => '腫瘍学'],
            ]
        );

        // 別解がないもの
        $bulk = [];
        $count = DB::table('japanese_terms')->count();
        $index = 1;
        for (; $index <= $count;) {
            $bulk[] = ['japanese_term_id' => $index, 'english_term_id' => $index];
            $index++;
        }
        DB::table('terms')->insert($bulk);


        // 日本語の別解あり
        $japanese_terms = [
            ['term' => '拒食症', 'department' => '消化器'],
            ['term' => '食欲低下', 'department' => '消化器'],
        ];
        $english_terms = [
            ['term' => 'anorexia', 'department' => '消化器'],
        ];

        DB::table('japanese_terms')->insert($japanese_terms);
        DB::table('english_terms')->insert($english_terms);


        $bulk = [];
        $eInx = $index;
        $jInx = $index;
        for ($i = 0; $i < 1; $i++) {
            $bulk[] = ['japanese_term_id' => $jInx, 'english_term_id' => $eInx];
            $bulk[] = ['japanese_term_id' => $jInx + 1, 'english_term_id' => $eInx];
            $eInx += 1;
            $jInx += 2;
        }
        DB::table('terms')->insert($bulk);
        
        // 英語の別解あり
        $japanese_terms = [
            ['term' => '鼓膜', 'department' => '耳鼻咽喉科'],
            ['term' => '脳卒中', 'department' => '神経'],
            ['term' => '吸引', 'department' => '総論'],
            ['term' => '妊娠', 'department' => '産婦人科'],
            ['term' => '分娩', 'department' => '産婦人科'],
            ['term' => '子宮筋腫',  'department' => '産婦人科'],
            ['term' => '脱毛症', 'department' => '皮膚科'],
            ['term' => '精巣', 'department' => '泌尿器科'],
            ['term' => '造影剤', 'department' => '放射線科'],
        ];

        $english_terms = [
            ['term' => 'eardrum', 'department' => '耳鼻咽喉科'],
            ['term' => 'tympanic membrane', 'department' => '耳鼻咽喉科'],
            ['term' => 'apoplexy', 'department' => '神経'],
            ['term' => 'stroke', 'department' => '神経'],
            ['term' => 'aspiration', 'department' => '総論'],
            ['term' => 'suction', 'department' => '総論'],
            ['term' => 'gestation', 'department' => '産婦人科'],
            ['term' => 'pregnancy', 'department' => '産婦人科'],
            ['term' => 'delivery', 'department' => '産婦人科'],
            ['term' => 'confinement', 'department' => '産婦人科'],
            ['term' => 'uterine myoma', 'department' => '産婦人科'],
            ['term' => 'uterine fibroid', 'department' => '産婦人科'],
            ['term' => 'baldness', 'department' => '皮膚科'],
            ['term' => 'alopecia', 'department' => '皮膚科'],
            ['term' => 'testis', 'department' => '泌尿器科'],
            ['term' => 'testicle', 'department' => '泌尿器科'],
            ['term' => 'contrast media', 'department' => '放射線科'],
            ['term' => 'contrast agent', 'department' => '放射線科'],
        ];

        DB::table('japanese_terms')->insert($japanese_terms);
        DB::table('english_terms')->insert($english_terms);

        $bulk = [];
        for ($i = 0; $i < 9; $i++) {
            $bulk[] = ['japanese_term_id' => $jInx, 'english_term_id' => $eInx];
            $bulk[] = ['japanese_term_id' => $jInx, 'english_term_id' => $eInx + 1];
            $eInx += 2;
            $jInx += 1;
        }
        DB::table('terms')->insert($bulk);
    }
}
