version: "3"

services:
 web:
    container_name: web
    build: ./web
    ports:
        - 8080:80
    volumes:
        - ./logs:/var/log/nginx
    depends_on:
        - app
 app:
    container_name: app
    build: ./app
    volumes:
        - ./logs:/var/www/meditan/storage/logs
    depends_on:
        - db
 db:
    container_name: db
    build: ./db
    ports:
      - 3306:3306
    volumes:
        - ./logs:/var/log/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: meditan
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret


