version: "3"

services:
 web:
    build: ./web
    ports:
        - 8080:80
    depends_on:
        - app
    volumes:
        - ./logs:/var/log/nginx
    links:
        - app
 app:
    build: ./app
 db:
    build: ./db
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: master
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: meditan
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

