# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#
#
#
#

Test.create(name_jp: "空腸", name_en: "jejunum")
Test.create(name_jp: "回腸", name_en: "ileum")
Test.create(name_jp: "盲腸", name_en: "cecum")
Test.create(name_jp: "憩室", name_en: "diverticulum")
Test.create(name_jp: "消化器学", name_en: "gastroenterology")
Test.create(name_jp: "空腸", name_en: "jejunum")
Test.create(name_jp: "回腸", name_en: "ileum")
Test.create(name_jp: "盲腸", name_en: "cecum")
Test.create(name_jp: "憩室", name_en: "diverticulum")
Test.create(name_jp: "消化", name_en: "digestion")
Test.create(name_jp: "無食欲", name_en: "anorexia")
Test.create(name_jp: "嚥下障害", name_en: "dysphagia")
Test.create(name_jp: "胸やけ", name_en: "heartburn")
Test.create(name_jp: "吐血", name_en: "hematemesis")
Test.create(name_jp: "下血", name_en: "melenak")
Test.create(name_jp: "便秘", name_en: "constipation")
Test.create(name_jp: "腹部膨満感", name_en: "bloating")
Test.create(name_jp: "膨隆", name_en: "protrusion")
Test.create(name_jp: "消化不良", name_en: "indigestion")
Test.create(name_jp: "胃食道逆流症", name_en: "gastroesophageal reflux disease")
Test.create(name_jp: "食道静脈瘤", name_en: "esophageal varix")
Test.create(name_jp: "腸重積", name_en: "intussusception")
Test.create(name_jp: "潰瘍性大腸炎", name_en: "ulcerative colitis")
Test.create(name_jp: "汎発性腹膜炎", name_en: "Pan-peritonitis")
Test.create(name_jp: "過敏性腸症候群", name_en: "irritable bowel syndrome")
Test.create(name_jp: "痔核", name_en: "hemorrhoid")
Test.create(name_jp: "総胆管", name_en: "common bile duct")
Test.create(name_jp: "胆嚢管", name_en: "cystic duct")
Test.create(name_jp: "胆汁", name_en: "bile")
Test.create(name_jp: "腹水", name_en: "ascites")
Test.create(name_jp: "黄疸", name_en: "jaundice,icterus")
Test.create(name_jp: "肝性脳症", name_en: "hepatic encephalopathy")
Test.create(name_jp: "胆管炎", name_en: "cholangitis")
Test.create(name_jp: "胆嚢炎", name_en: "cholecystitis")

Question.create(name_jp: "空腸", name_en: "jejunum")
Question.create(name_jp: "回腸", name_en: "ileum")
Question.create(name_jp: "盲腸", name_en: "cecum")
Question.create(name_jp: "憩室", name_en: "diverticulum")
Question.create(name_jp: "消化器学", name_en: "gastroenterology")
Question.create(name_jp: "空腸", name_en: "jejunum")
Question.create(name_jp: "回腸", name_en: "ileum")
Question.create(name_jp: "盲腸", name_en: "cecum")
Question.create(name_jp: "憩室", name_en: "diverticulum")
Question.create(name_jp: "消化", name_en: "digestion")
Question.create(name_jp: "無食欲", name_en: "anorexia")
Question.create(name_jp: "嚥下障害", name_en: "dysphagia")
Question.create(name_jp: "胸やけ", name_en: "heartburn")
Question.create(name_jp: "吐血", name_en: "hematemesis")
Question.create(name_jp: "下血", name_en: "melenak")
Question.create(name_jp: "便秘", name_en: "constipation")
Question.create(name_jp: "腹部膨満感", name_en: "bloating")
Question.create(name_jp: "膨隆", name_en: "protrusion")
Question.create(name_jp: "消化不良", name_en: "indigestion")
Question.create(name_jp: "胃食道逆流症", name_en: "gastroesophageal reflux disease")
Question.create(name_jp: "食道静脈瘤", name_en: "esophageal varix")
Question.create(name_jp: "腸重積", name_en: "intussusception")
Question.create(name_jp: "潰瘍性大腸炎", name_en: "ulcerative colitis")
Question.create(name_jp: "汎発性腹膜炎", name_en: "Pan-peritonitis")
Question.create(name_jp: "過敏性腸症候群", name_en: "irritable bowel syndrome")
Question.create(name_jp: "痔核", name_en: "hemorrhoid")
Question.create(name_jp: "総胆管", name_en: "common bile duct")
Question.create(name_jp: "胆嚢管", name_en: "cystic duct")
Question.create(name_jp: "胆汁", name_en: "bile")
Question.create(name_jp: "腹水", name_en: "ascites")
Question.create(name_jp: "黄疸", name_en: "jaundice,icterus")
Question.create(name_jp: "肝性脳症", name_en: "hepatic encephalopathy")
Question.create(name_jp: "胆管炎", name_en: "cholangitis")
Question.create(name_jp: "胆嚢炎", name_en: "cholecystitis")
